dist: xenial
language: python
python:
  - "3.8"
  - "3.9"
branches:
  only:
  - main
# command to install dependencies
install:
  - pip install flake8
script:
  - run flake8
  - bash sonar_scanner.sh
